name: Update Highlights Every Hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [manual_push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Highlights Generator
        env:
          LIVXOW_URL: ${{ secrets.LIVXOW_URL }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ivan.json
          git commit -m "Update ivan.json [Skip CI]" || exit 0
          git push
